#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x154343260542DF34 (brandon@ifup.co)
#
Name     : acl
Version  : 2.2.52
Release  : 31
URL      : http://download.savannah.gnu.org/releases/acl/acl-2.2.52.src.tar.gz
Source0  : http://download.savannah.gnu.org/releases/acl/acl-2.2.52.src.tar.gz
Source99 : http://download.savannah.gnu.org/releases/acl/acl-2.2.52.src.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0+ LGPL-2.1
Requires: acl-bin
Requires: acl-lib
Requires: acl-doc
Requires: acl-locales
BuildRequires : attr-dev
BuildRequires : attr-dev32
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32

%description
__________________________________
Package home: http://savannah.nongnu.org/projects/acl

%package bin
Summary: bin components for the acl package.
Group: Binaries

%description bin
bin components for the acl package.


%package dev
Summary: dev components for the acl package.
Group: Development
Requires: acl-lib
Requires: acl-bin
Provides: acl-devel

%description dev
dev components for the acl package.


%package dev32
Summary: dev32 components for the acl package.
Group: Default
Requires: acl-lib32
Requires: acl-bin
Requires: acl-dev

%description dev32
dev32 components for the acl package.


%package doc
Summary: doc components for the acl package.
Group: Documentation

%description doc
doc components for the acl package.


%package lib
Summary: lib components for the acl package.
Group: Libraries

%description lib
lib components for the acl package.


%package lib32
Summary: lib32 components for the acl package.
Group: Default

%description lib32
lib32 components for the acl package.


%package locales
Summary: locales components for the acl package.
Group: Default

%description locales
locales components for the acl package.


%prep
%setup -q -n acl-2.2.52
pushd ..
cp -a acl-2.2.52 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1495409179
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto -fno-semantic-interposition "
%configure --disable-static --enable-nls \
--libexecdir=%{_libdir} \
--disable-static \
--enable-shared
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static --enable-nls \
--libexecdir=%{_libdir} \
--disable-static \
--enable-shared   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%install
export SOURCE_DATE_EPOCH=1495409179
rm -rf %{buildroot}
pushd ../build32/
%make_install32 install-lib install-dev DIST_ROOT=%{buildroot} DESTDIR=%{buildroot}
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install install-lib install-dev DIST_ROOT=%{buildroot} DESTDIR=%{buildroot}
%find_lang acl

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/chacl
/usr/bin/getfacl
/usr/bin/setfacl

%files dev
%defattr(-,root,root,-)
/usr/include/acl/libacl.h
/usr/include/sys/acl.h
/usr/lib64/libacl.so

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libacl.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/acl/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
%doc /usr/share/man/man5/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libacl.so.1
/usr/lib64/libacl.so.1.1.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libacl.so.1
/usr/lib32/libacl.so.1.1.0

%files locales -f acl.lang
%defattr(-,root,root,-)

